<a href="https://colab.research.google.com/github/Abhulimen/Assignment7/blob/main/Copy_of_Assignment_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 7 (Week 7)

>**Note**: 

```
- Late submissions are penalized.
- Only GitHub submissions are acceptable.
```

## Name: Paulina Victor

<br>

## Please show and display ALL your calculations and results.
> Remember to read the **`instructions`** carefully.

In [ ]:
# Built-in library
import itertools

# Standard imports
import numpy as np
import pandas as pd


# pandas settings
pd.options.display.max_rows = 1_000
pd.options.display.max_columns = 1_000
pd.options.display.max_colwidth = 1_000


# Black code formatter (Optional)
#%load_ext lab_black

> The data can be found [here](https://drive.google.com/file/d/1_c3KA14xQC02K0QZ4cpi1emjdz0rqHzb/view?usp=share_link).

### Data Dictionary

```
- Age: continuous.

- Workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.

- Final_weight: continuous.

- Education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, - Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.

- Education_num: continuous.

- Marital_status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, - Married-AF-spouse.

- Occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.

- Relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.

- Race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.

- Genger: Female, Male.

- Capital_gain: continuous.

- Capital_loss: continuous.

- Hours_per_week: continuous.

- Country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

- Salary: 
```

### Objective

```
Predict whether a person makes over 50K a year.

```



###  Qs 1. Build a machine learning model that predicts the salary.

###  Qs 2. Evaluate the performance of your model using at least three (3) performance metrics.

<hr>

## Note: 

- The assignment **should** be submitted through a `public` GitHub repository.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer

In [ ]:
df = pd.read_csv('salary.csv')
df.head()

Age          Workclass  Final_weight   Education  Education_num  \
0   50   Self-emp-not-inc         83311   Bachelors             13   
1   38            Private        215646     HS-grad              9   
2   53            Private        234721        11th              7   
3   28            Private        338409   Bachelors             13   
4   37            Private        284582     Masters             14   

        Marital_status          Occupation    Relationship    Race      Sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   Capital_gain  Capital_loss  Hours_per_week         Country  Salary  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

**Data exploration before model building**

In [ ]:
df.isna().sum()

Age               0
Workclass         0
Final_weight      0
Education         0
Education_num     0
Marital_status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital_gain      0
Capital_loss      0
Hours_per_week    0
Country           0
Salary            0
dtype: int64

In [ ]:
num_var = df.select_dtypes(exclude='O')
car_var = df.select_dtypes(include='O')
car_var.shape, num_var.shape

((32560, 9), (32560, 6))

In [ ]:
vars_to_scale = num_var.columns
vars_to_enc = car_var.columns
# ===== OHE =====
ohe = OneHotEncoder(dtype=int, handle_unknown="ignore", sparse_output=False)

# ===== Scaler =====
scaler = MinMaxScaler()

col_transformer = ColumnTransformer(
    transformers=[("ohe", ohe, vars_to_enc), ("scaler", scaler, vars_to_scale)],
    remainder="passthrough",
)

col_transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(dtype=<class 'int'>,
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 Index(['Workclass', 'Education', 'Marital_status', 'Occupation',
       'Relationship', 'Race', 'Sex', 'Country', 'Salary'],
      dtype='object')),
                                ('scaler', MinMaxScaler(),
                                 Index(['Age', 'Final_weight', 'Education_num', 'Capital_gain', 'Capital_loss',
       'Hours_per_week'],
      dtype='object'))])

In [ ]:
trainer = col_transformer.fit_transform(df)
trainer

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.12244898],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.39795918],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.39795918],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.39795918],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.19387755],
       [0.        , 0.        , 0.        , ..., 0.1502415 , 0.        ,
        0.39795918]])

In [ ]:
df = pd.DataFrame(trainer, columns=col_transformer.get_feature_names_out())
df.head()

ohe__Workclass_ ?  ohe__Workclass_ Federal-gov  ohe__Workclass_ Local-gov  \
0                0.0                          0.0                        0.0   
1                0.0                          0.0                        0.0   
2                0.0                          0.0                        0.0   
3                0.0                          0.0                        0.0   
4                0.0                          0.0                        0.0   

   ohe__Workclass_ Never-worked  ohe__Workclass_ Private  \
0                           0.0                      0.0   
1                           0.0                      1.0   
2                           0.0                      1.0   
3                           0.0                      1.0   
4                           0.0                      1.0   

   ohe__Workclass_ Self-emp-inc  ohe__Workclass_ Self-emp-not-inc  \
0                           0.0                               1.0   
1                           0.0                               0.0   
2                           0.0                               0.0   
3                           0.0                               0.0   
4                           0.0                               0.0   

   ohe__Workclass_ State-gov  ohe__Workclass_ Without-pay  \
0                        0.0                          0.0   
1                        0.0                          0.0   
2                        0.0                          0.0   
3                        0.0                          0.0   
4                        0.0                          0.0   

   ohe__Education_ 10th  ohe__Education_ 11th  ohe__Education_ 12th  \
0                   0.0                   0.0                   0.0   
1                   0.0                   0.0                   0.0   
2                   0.0                   1.0                   0.0   
3                   0.0                   0.0                   0.0   
4                   0.0                   0.0                   0.0   

   ohe__Education_ 1st-4th  ohe__Education_ 5th-6th  ohe__Education_ 7th-8th  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   ohe__Education_ 9th  ohe__Education_ Assoc-acdm  ohe__Education_ Assoc-voc  \
0                  0.0                         0.0                        0.0   
1                  0.0                         0.0                        0.0   
2                  0.0                         0.0                        0.0   
3                  0.0                         0.0                        0.0   
4                  0.0                         0.0                        0.0   

   ohe__Education_ Bachelors  ohe__Education_ Doctorate  \
0                        1.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        1.0                        0.0   
4                        0.0                        0.0   

   ohe__Education_ HS-grad  ohe__Education_ Masters  \
0                      0.0                      0.0   
1                      1.0                      0.0   
2                      0.0                      0.0   
3                      0.0                      0.0   
4                      0.0                      1.0   

   ohe__Education_ Preschool  ohe__Education_ Prof-school  \
0                        0.0                          0.0   
1                        0.0                          0.0   
2                        0.0                          0.0   
3                        0.0                          

In [ ]:
df.shape

(32560, 110)

In [ ]:
df['ohe__Salary_ <=50K'].head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: ohe__Salary_ <=50K, dtype: float64

In [ ]:
 df['ohe__Salary_ <=50K'].head(2)

0    1.0
1    1.0
Name: ohe__Salary_ <=50K, dtype: float64

In [ ]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex_

In [ ]:
target = ['ohe__Salary_ <=50K', 'ohe__Salary_ >50K']
X = df.drop(target, axis='columns')
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=123, shuffle=True)
X_train.shape, X_test.shape, y_train.shape

((26048, 108), (6512, 108), (26048, 2))

*model building and training to make predictions*

In [ ]:
#Instantiate
linear_model = LinearRegression()
# Fit
linear_model.fit(X_train, y_train)

# Make Predictions
y_pred_1 = linear_model.predict(X_test)
np.round(y_pred_1)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
y_test, np.round(y_pred_1)

(       ohe__Salary_ <=50K  ohe__Salary_ >50K
 20712                 1.0                0.0
 13495                 1.0                0.0
 12367                 1.0                0.0
 22401                 0.0                1.0
 18338                 1.0                0.0
 ...                   ...                ...
 11027                 1.0                0.0
 53                    1.0                0.0
 26921                 1.0                0.0
 24671                 1.0                0.0
 29238                 0.0                1.0
 
 [6512 rows x 2 columns],
 array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]))

**Predicting those that earn above 50K salary**

In [ ]:
salary_above_50 = np.where(np.round(y_pred_1)[:, 1] == 1)
salary_above_50

(array([   3,    7,   18, ..., 6497, 6503, 6505]),)

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn import metrics

**model evaluation**

In [ ]:
mse = mean_squared_error(y_true=y_test, y_pred=y_pred_1, squared=True)
mse

0.11414368095503392

In [ ]:
rs = r2_score(y_true=y_test, y_pred=y_pred_1)
rs

0.36840323767907596

In [ ]:
mae = mean_absolute_error(y_true=y_test, y_pred=y_pred_1)
mae

0.26275477303919687

**The lower the better for mse and mae, but the higher the better for rs. Only mse is looking like a good model evaluation for my model or maybe there is somethiong i'm not getting right**